language: php

php:
    - 7.4
    - 8.1

before_script:
    - composer self-update
    - composer update --dev -o -n
    - echo 'xdebug.max_nesting_level = 10000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - php bin/console benchcart --count 1 --by 10000
    - php bin/console benchcart --count 2 --by 1000
    - php bin/console benchcart --count 3 --by 100
    - php bin/console benchcart --count 4 --by 30
    - php bin/console benchcart --count 5 --by 15
    - php bin/console benchcart --count 10 --by 4
    - php bin/console benchcart --count 5000 --by 1
