language: php

php:
    - 7.1

before_script:
    - composer self-update
    - composer update --dev -o -n

script:
    - php bin/console benchcart --count 1 --by 1
    - php bin/console benchcart --count 1 --by 1000
    - php bin/console benchcart --count 1000 --by 1
    - php bin/console benchcart --count 100 --by 100
