language: php

php:
    - nightly

before_script:
    - composer self-update
    - composer update --dev -o -n --ignore-platform-reqs

script:
    - php bin/console benchcart --count 1 --by 1
    - php bin/console benchcart --count 1 --by 1000
    - php bin/console benchcart --count 1000 --by 1
    - php bin/console benchcart --count 100 --by 100
