language: php

php:
    - 7.1

before_script:
    - composer self-update
    - composer update --dev -o -n

script:
    - php bin/console benchcart --count 1 --by 1
    - php bin/console benchcart --count 1 --by 250
    - php bin/console benchcart --count 250 --by 1
    - php bin/console benchcart --count 15 --by 15
