language: php

php:
    - 7.1

before_script:
    - composer self-update
    - composer update --dev -o -n
    - echo 'xdebug.max_nesting_level = 1000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - php bin/console benchcart --count 1 --by 1
    - php bin/console benchcart --count 1 --by 250
    - php bin/console benchcart --count 250 --by 1
    - php bin/console benchcart --count 5 --by 5
